# Generated by Django 4.2.1 on 2023-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addtocart',
            options={'verbose_name_plural': 'Add to cart'},
        ),
    ]
