# Generated by Django 4.2.1 on 2023-06-30 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartsystem', '0003_addtocart_created_at_addtocart_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddToCart',
            new_name='Cart',
        ),
    ]
