# Generated by Django 4.2.3 on 2023-07-07 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartsystem', '0004_rename_addtocart_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
    ]
