# Generated by Django 4.2.3 on 2023-08-21 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartsystem', '0009_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='active',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
