# Generated by Django 4.2.1 on 2023-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('message', models.TextField()),
                ('recipient', models.CharField(max_length=32)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
