# Generated by Django 4.2.3 on 2023-07-09 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_delivery_created_at_delivery_updated_at'),
        ('cartsystem', '0006_cart_products'),
        ('orders', '0002_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cartsystem.cart'),
        ),
        migrations.AddField(
            model_name='order',
            name='logistics',
            field=models.ManyToManyField(to='logistics.delivery'),
        ),
    ]
