# Generated by Django 4.2.1 on 2023-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('password', models.CharField(max_length=6, verbose_name='Password')),
                ('storename', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
