# Generated by Django 4.2.1 on 2023-06-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(max_length=32)),
                ('delivery_method', models.TextField()),
                ('duration', models.DurationField()),
                ('delivery_address', models.CharField(max_length=200)),
            ],
        ),
    ]
