# Generated by Django 4.2.1 on 2023-06-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Custom Name'},
        ),
    ]
