# Generated by Django 4.2.1 on 2023-06-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_delivery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Delivery'},
        ),
    ]
