# Generated by Django 4.2.3 on 2023-07-07 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_vendor_created_at_vendor_updated_at'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owner.vendor'),
            preserve_default=False,
        ),
    ]
