# Generated by Django 4.2.3 on 2023-07-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_vendor_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='path/', verbose_name='img'),
        ),
    ]
