# Generated by Django 4.2.3 on 2023-08-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
